SELECT REST_ID, F.REST_NAME, F.FOOD_TYPE, F.FAVORITES, F.ADDRESS,
        ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO F JOIN REST_REVIEW R USING(REST_ID)
WHERE F.ADDRESS LIKE '서울%'
GROUP BY REST_ID, F.REST_NAME, F.FOOD_TYPE, F.FAVORITES, F.ADDRESS
ORDER BY SCORE DESC, F.FAVORITES DESC;